/**
 * jekyll-redirect-from.test.js — JS port of jekyll-redirect-from v0.16.0.
 *
 * Verifies the native JS implementation matches the real Ruby gem's behavior:
 * - redirect_from front matter generates redirect pages
 * - redirect_to front matter makes the page itself redirect
 * - redirects.json is generated (unless disabled)
 *
 * Ground truth: real jekyll-redirect-from 0.16.0 via native Ruby oracle.
 */
import { JekyllEngine } from '../../src/engine.js';

describe('jekyll-redirect-from (JS port of Ruby gem v0.16.0)', () => {
  const makeEngine = (vfs) => new JekyllEngine({
    vfs: {
      '_config.yml': 'plugins:\n  - jekyll-redirect-from\n',
      ...vfs,
    },
    logger: () => {},
  });

  test('redirect_from generates a redirect page', async () => {
    const engine = makeEngine({
      'index.md': '---\n---\nHome.',
      'old-page.md': '---\nredirect_from: /old-url/\n---\nNew content.',
    });
    const pages = await engine.build();
    const redirect = pages.find((p) => p.permalink === '/old-url/');
    expect(redirect).toBeDefined();
    expect(redirect.content).toContain('<title>Redirecting&hellip;</title>');
    expect(redirect.content).toContain('href="/old-page.html"');
    expect(redirect.content).toContain('location="/old-page.html"');
    expect(redirect.data.sitemap).toBe(false);
  });

  test('redirect_from accepts an array of paths', async () => {
    const engine = makeEngine({
      'index.md': '---\n---\nHome.',
      'new.md': '---\nredirect_from:\n  - /old1/\n  - /old2/\n---\nNew.',
    });
    const pages = await engine.build();
    expect(pages.some((p) => p.permalink === '/old1/')).toBe(true);
    expect(pages.some((p) => p.permalink === '/old2/')).toBe(true);
  });

  test('redirect_to makes the page itself redirect', async () => {
    const engine = makeEngine({
      'index.md': '---\n---\nHome.',
      'external.md': '---\nredirect_to: https://example.com/\n---\nWill redirect.',
    });
    const pages = await engine.build();
    const page = pages.find((p) => p.permalink === '/external.html');
    expect(page).toBeDefined();
    expect(page.content).toContain('location="https://example.com/"');
    expect(page.content).toContain('<meta name="robots" content="noindex">');
  });

  test('redirects.json is generated by default', async () => {
    const engine = makeEngine({
      'index.md': '---\n---\nHome.',
      'old.md': '---\nredirect_from: /old/\n---\nNew.',
    });
    const pages = await engine.build();
    const json = pages.find((p) => p.permalink === '/redirects.json');
    expect(json).toBeDefined();
    const data = JSON.parse(json.content);
    expect(data['/old/']).toBe('/old.html');
  });

  test('redirect HTML matches Ruby gem byte-for-byte', async () => {
    // Ground truth from real jekyll-redirect-from 0.16.0 via native oracle:
    // /tmp/redirect-native/old-url/index.html
    const expected = `<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting&hellip;</title>
  <link rel="canonical" href="/old-page.html">
  <script>location="/old-page.html"</script>
  <meta http-equiv="refresh" content="0; url=/old-page.html">
  <meta name="robots" content="noindex">
  <h1>Redirecting&hellip;</h1>
  <a href="/old-page.html">Click here if you are not redirected.</a>
</html>
`;
    const engine = makeEngine({
      'index.md': '---\n---\nHome.',
      'old-page.md': '---\nredirect_from: /old-url/\n---\nContent.',
    });
    const pages = await engine.build();
    const redirect = pages.find((p) => p.permalink === '/old-url/');
    expect(redirect.content).toBe(expected);
  });
});
